config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'flats#index'
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController

  def index
    if params[:query_string]
      @flats = Flat.where("name LIKE ?", "%#{params[:query_string]}%")
    else 
      @flats = Flat.all
    end
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    if @flat.save
      redirect_to flats_path
    else
      render :new
    end
  end
  private

  def flat_params

    params.require(:flat).permit(:name, :address, :descritpion, :price_per_night, :number_of_guests)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<h1 class = "mt-3"> Tous nos appartements (<%= @flats.count%>)</h1>
<div class = "flats">
  <% @flats.each do |flat| %>
    <div class = "flat-card">
      <div class = "flat-info">
        <h3><%= flat.name %></h3>
        <p><%= flat.address %></p>
        <i class="fas fa-user-friends"></i>
        <span><%= flat.number_of_guests %></span> 
        <i class="fas fa-euro-sign"></i>
        <span><%= flat.price_per_night %></span>
      </div>
      <%= link_to "voir l'appartement", flat_path(flat), class: "flat-link" %>
    </div>
  <% end %>
  </div>
</div>

app/views/flats/new.html.erb
<div class="mx-3 mt-3">
  <%= simple_form_for(@flat) do |f|%>
    <%= f.input :name %>
    <%= f.input :address%>
    <%= f.input :price_per_night %>
    <%= f.input :number_of_guests %>
    <%= f.submit "Ajouter l'appartement", class:"btn btn-primary" %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AirBnb</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Home", root_path , class: "nav-link" %>
      </li>
      <li class="nav-item active mr-2">
        <%= link_to "Ajouter un appartement", new_flat_path,  class: "nav-link" %> 
      </li>
      <form class="form-inline">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name ="query_string">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
    </ul>
  </div>
</div>